### ISSUE TITLE
你好，特征融合效果的热力图如何实现呢？

### ISSUE THREAD

**Issue by gxyup** [zhaoxing2022/MMN-VSOD#1]

**Comment by aflyingnoob** [comment]
您好，您是想在自己论文里画这种图吗？做法大概是先用一些看特征图的工具吧特征图存起来，然后设置下透明度盖在原图上就行了。

**Comment by zhaoxing2022** [comment]
您好，您是想在自己论文里画这种图吗？做法大概是先用一些看特征图的工具吧特征图存起来，然后设置下透明度盖在原图上就行了。

**Comment by gxyup** [comment]
感谢

**Comment by gxyup** [comment]
很抱歉再次打扰您，我做出来的效果不理想。如果方便的话，可以让我参考下这部分的实验代码吗？
我的邮箱是gaoxueyuangxy@163.com

**Comment by zhaoxing2022** [comment]
我用ppt画的，特征图用存好了盖在原图上重合，设置透明度40%
